In [1]:
import pandas as pd
import seaborn as sns

In [2]:
data = pd.read_csv("Iris.csv")

In [3]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [5]:
print("\nStatistical Details for each species:\n")
data.groupby('Species').describe()

Statistical Details for each species:

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [6]:
print("\nMean and Standard Deviation:\n")
data.groupby('Species').agg(['mean', 'std'])

Mean and Standard Deviation:

                    Id           SepalLengthCm           SepalWidthCm  \
                  mean       std          mean       std         mean
Species
Iris-setosa       25.5  14.57738         5.006  0.352490        3.418
Iris-versicolor   75.5  14.57738         5.936  0.516171        2.770
Iris-virginica   125.5  14.57738         6.588  0.635880        2.974

                          PetalLengthCm           PetalWidthCm
                      std          mean       std         mean       std
Species
Iris-setosa      0.381024         1.464  0.173511        0.244  0.107210
Iris-versicolor  0.313798         4.260  0.469911        1.326  0.197753
Iris-virginica   0.322497         5.552  0.551895        2.026  0.274650

In [8]:
# Percentiles (25%, 50%, 75%)
print("\nPercentiles (25%, 50%, 75%):\n")
data.groupby('Species').quantile([0.25, 0.5, 0.75])

Percentiles (25%, 50%, 75%):

                          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa     0.25   13.25          4.800         3.125          1.400
                0.50   25.50          5.000         3.400          1.500
                0.75   37.75          5.200         3.675          1.575
Iris-versicolor 0.25   63.25          5.600         2.525          4.000
                0.50   75.50          5.900         2.800          4.350
                0.75   87.75          6.300         3.000          4.600
Iris-virginica  0.25  113.25          6.225         2.800          5.100
                0.50  125.50          6.500         3.000          5.550
                0.75  137.75          6.900         3.175          5.875

                      PetalWidthCm
Species
Iris-setosa     0.25           0.2
                0.50           0.2
                0.75           0.3
Iris-versicolor 0.25           1.2
                0.50           1.3
                0.75           1.5
Iris-virginica  0.25           1.8
                0.50           2.0
                0.75           2.3